routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EmployeeController;
use App\Salida;

Route::get('/', function () {
  return redirect('login');
});

Auth::routes();

/* Rutas estaticas */
Route::get('home', 'HomeController@index')->name('home');
Route::get('dashboard', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('role', 'RoleController', ['except' => ['show', 'destroy']]);
    Route::resource('user', 'UserController', ['except' => ['show']]);
    
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

    Route::resource('almacen','AlmacenController');
    Route::resource('proveedor','ProveedorController');
    Route::resource('mensajero','MensajeroController');
    Route::resource('rack','RackController');
    Route::resource('ubicacion','UbicacionController');
    Route::resource('entrada','EntradaController');
    Route::resource('cliente','ClienteController');
    Route::resource('tipocaja','TipoCajaController');
    Route::resource('paqueteria','PaqueteriaController');
    Route::resource('detalle_entrada','DetalleEntradaController');
    Route::resource('materiales','MaterialController');
    Route::resource('producto','ProductoController');
    Route::resource('lote_producto','LoteProductoController');
    Route::resource('recolector','RecolectorController');

    Route::resource('estatus_factura','EstatusFacturaController');
    Route::resource('tipo_entrada','TipoEntradaController');
    Route::resource('conductor','ConductorController');    
    Route::resource('tipo_salida','TipoSalidaController');
    Route::resource('familia_producto','FamiliaProductoController');
    Route::resource('tipo_envio','TipoEnvioController');
    Route::resource('salida','SalidaController');    
    Route::resource('factura','FacturaController');   
    Route::resource('detalle_factura','DetalleFacturaController');

    Route::get('guia/{guia}/{factura}/edit','GuiaController@edit')->name('guia.editar');

    Route::resource('guia','GuiaController');
    Route::resource('ruta_embarque','RutaEmbarqueController');
    Route::post('/producto/imprimir/etiqueta',[App\Http\Controllers\ProductoController::class, 'getImprimirEtiquetas'])->name('producto.imprimir.etiqueta');
    Route::get('/producto/info/etiqueta',[App\Http\Controllers\ProductoController::class, 'getInfoEtiquetas'])->name('producto.info.etiqueta');
    Route::post('/rack/imprimir/etiqueta',[App\Http\Controllers\RackController::class, 'getImprimirEtiquetas'])->name('rack.imprimir.etiqueta');
    Route::get('/rack/info/etiqueta',[App\Http\Controllers\RackController::class, 'getInfoEtiquetas'])->name('rack.info.etiqueta');
    Route::get('/facturas/notificacion', [App\Http\Controllers\FacturaController::class, 'getFacturasPorSurtir'])->name('facturas.notificacion');
    Route::get('/facturas/notificacion', [App\Http\Controllers\FacturaController::class, 'getFacturasPorSurtir'])->name('facturas.notificacion');
    Route::get('/facturas/detalles', [App\Http\Controllers\FacturaController::class, 'getDetalle'])->name('facturas.detalles');
    Route::get('/facturas/crear_detalle/{id_factura}', [App\Http\Controllers\FacturaController::class, 'create_detalle'])->name('facturas.detalle_create');
    Route::get('/facturas/filtros', [App\Http\Controllers\FacturaController::class, 'filtros'])->name('facturas.filtros');
    Route::get('/facturas/consulta/filtros', [App\Http\Controllers\FacturaController::class, 'consultaFacturas'])->name('facturas.consulta');
    Route::get('/factura/{factura}/show', [App\Http\Controllers\FacturaController::class, 'showFactura'])->name('facturas.show');
    Route::get('/entrada/crear/detalle/{entrada}', [App\Http\Controllers\DetalleEntradaController::class, 'createDetalle'])->name('entrada.create.detalle');
    Route::get('/producto/crear/lote/{producto}', [App\Http\Controllers\LoteProductoController::class, 'createLote'])->name('producto.create.lote');
    Route::get('/home/consulta', [App\Http\Controllers\HomeController::class, 'consulta'])->name('consulta');
    Route::get('/home/consulta_factura', [App\Http\Controllers\HomeController::class, 'consulta_factura'])->name('consulta_factura');
    Route::get('/home/consulta_pie', [App\Http\Controllers\HomeController::class, 'consulta_pie'])->name('consulta_pie');
    Route::post('/salida/estatus/mensajero',[App\Http\Controllers\SalidaController::class, 'getEstatusMensajero'])->name('salida.estatus.mensajero');
    Route::post('/salida/asignacion/mensajero',[App\Http\Controllers\SalidaController::class, 'getAsignacionMensajero'])->name('salida.asignacion.mensajero');
    Route::post('/guia/imprimir/etiqueta',[App\Http\Controllers\GuiaController::class, 'getImprimirEtiquetas'])->name('guia.imprimir.etiqueta');
    Route::get('/guia/info/etiqueta',[App\Http\Controllers\GuiaController::class, 'getInfoEtiquetas'])->name('guia.info.etiqueta');

    Route::get('/visita', 'VisitaController@visita')->name('visita');
    Route::get('/tipocajas', 'VisitaController@tipoCajas')->name('tipocajas');
    Route::get('/tipo_entradas/{entrada}', 'VisitaController@tipoEntradas')->name('tipoentradas');
    Route::get('/detalle_entradas', 'VisitaController@detalleEntradas')->name('detalle_entradas');

    Route::get('/entradas/{tipo}', 'VisitaController@entradas')->name('entradas2');
    Route::get('/proveedores/{entrada}', 'VisitaController@proveedores')->name('proveedores');
    Route::get('/familia_productos/{producto}', 'VisitaController@familiaProductos')->name('familia_productos');
    Route::get('/racks/{almacen}', 'VisitaController@racks')->name('racks');
    Route::get('/ubicaciones/{rack}', 'VisitaController@ubicaciones')->name('ubicaciones');

    Route::get('/facturas/subir', function () {return view('facturas.upload');})->name('facturas.upload');
    Route::post('/facturas/guardar', 'FacturaController@subirFactura')->name('factura.guardar');
    Route::get('/productos/subir', function () {return view('productos.upload');})->name('productos.upload');
    Route::post('/productos/guardar', 'ProductoController@subirProducto')->name('producto.guardar');
    Route::post('/productos/confirmar-producto', 'ProductoController@confirmarProducto')->name('producto.confirmar');
    //Primer Camino
    Route::get('/entradas/{opc}/{tipoE}','VisitaController@entradas')->name('entradas');
    Route::get('/proveedores/{opc}/{entrada}','VisitaController@proveedores')->name('proveedores');
    Route::get('/familia_productos/{opc}/{proveedor}','VisitaController@familiaProductos')->name('familia_productos');

    Route::get('/racks/{opc}/{dato}','VisitaController@racks')->name('racks');
    Route::get('/ubicaciones/{opc}/{dato}','VisitaController@ubicaciones')->name('ubicaciones');
    Route::get('/lote_productos/{opc}/{dato}','VisitaController@loteProductos')->name('lote_productos');

    Route::get('/productos','VisitaController@productos')->name('productos');
    Route::get('/salidas/mensajero', [App\Http\Controllers\SalidaController::class, 'mensajero'])->name('salidas.upload');
    Route::get('/salidas/amensajero', [App\Http\Controllers\SalidaController::class, 'amensajero'])->name('salidas.asignacion');
});


//Rutas Android
Route::post('/setToken','RecolectorController@setToken')->name('setToken');
Route::post('/arreglo','FacturaController@password');
Route::post('/por-surtir','FacturaController@getPorSurtir');
Route::post('/todas','FacturaController@getTodas');
Route::post('/get-factura','FacturaController@getFactura');
Route::post('/actualizar-factura','FacturaController@actualizarFactura');
Route::post('/recolectores','RecolectorController@getRecolectores')->name('recolectores');
Route::post('/ver-ubicaciones','UbicacionController@getUbicaciones');
Route::post('/ver-productos','ProductoController@getProductos');
Route::post('/subir-fotos','FacturaController@subirFotos');
Route::post('/actualizar-lote','UbicacionController@actualizarLote');
Route::post('/ver-detalles','DetalleFacturaController@getDetalles');

Route::post('/get-estatus-factura','EstatusFacturaController@getAllEstatus');
Route::post('/get-producto','ProductoController@getProducto');
Route::post('/get-ubicacion','UbicacionController@getUbicacion');
Route::post('/get-almacenes', function () {return App\ListHelper::getAllAlmacenes();});
Route::post('/get-via-embarques', function () {return App\ListHelper::getAllPaqueterias();});
Route::post('/actualizar-estatus-factura','FacturaController@actualizarEstatus');
// Route::get('/get-tipos-envio','EstatusFacturaController@getAllEstatus');


Route::post('/modificar-lotes','LoteProductoController@modificarLotes');
Route::post('/asignar-ubicacion','LoteUbicacionController@asignarUbicacionToProduct');
Route::post('/lotesByUbicacion','LoteProductoController@lotesByUbicacion');

app/TipoEnvio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TipoEnvio extends Model
{
    use HasFactory;
    protected $table = 'c_tipo_envio';
    protected $fillable = [
        'nombre',
        'capturado_por',
        'actualizado_por',
    ];
}

app/Http/Controllers/TipoEnvioController.php
<?php

namespace App\Http\Controllers;

use App\TipoEnvio;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TipoEnvioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $tipoEnvio = TipoEnvio::all();
        return view('tipo_envios.index', compact(["tipoEnvio","user"]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tipo_envios.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre'=>'required'
        ]);

        $request->request->add(['capturado_por' => Auth::user()->name]);
        $request->request->add(['actualizado_por' => Auth::user()->name]);

        TipoEnvio::create($request->all());
        return redirect()->route('tipo_envio.index')->withStatus(__('Registro creado correctamente.'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\TipoEnvio  $tipoEnvio
     * @return \Illuminate\Http\Response
     */
    public function show(TipoEnvio $tipoEnvio)
    {
        return view('tipo_envios.show', compact('tipoEnvio'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\TipoEnvio  $tipoEnvio
     * @return \Illuminate\Http\Response
     */
    public function edit(TipoEnvio $tipoEnvio)
    {
        return view('tipo_envios.edit', compact('tipoEnvio'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\TipoEnvio  $tipoEnvio
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, TipoEnvio $tipoEnvio)
    {
        $request->validate([
            'nombre'=>'required'
        ]);

        $request->request->add(['actualizado_por' => Auth::user()->name]);
        $tipoEnvio->update($request->all());
        return redirect()->route('tipo_envio.index')->withStatus(__('El registro fue actualizado.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\TipoEnvio  $tipoEnvio
     * @return \Illuminate\Http\Response
     */
    public function destroy(TipoEnvio $tipoEnvio)
    {
        $tipoEnvio->delete();
        return redirect()->route('tipo_envio.index')->withStatus(__('El registro fue borrado.'));
    }

}

resources/views/tipo_envios/create.blade.php
@extends('layouts.app', ['activePage' => 'envio', 'menuParent' => 'catalogos', 'titlePage' => __('Tipo Envio')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" enctype="multipart/form-data" action="{{ route('tipo_envio.store') }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('post')

            <div class="card ">
              <div class="card-header card-header-success card-header-icon">
                <div class="card-icon">
                  <i class="fas fa-shipping-fast fa-2x"></i>
                </div>
                <h4 class="card-title">Agregar Tipo</h4>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('tipo_envio.index') }}" class="btn btn-sm btn-success">{{ __('Regresar a la lista') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">Nombre</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('nombre') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('nombre') ? ' is-invalid' : '' }}" name="nombre" id="input-name" type="text" placeholder="Nombre" value="{{ old('nombre') }}" required="true" aria-required="true"/>
                      @include('alerts.feedback', ['field' => 'nombre'])
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-success">GUARDAR</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/tipo_envios/edit.blade.php
@extends('layouts.app', ['activePage' => 'envio', 'menuParent' => 'catalogos', 'titlePage' => __('Tipo envio')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" enctype="multipart/form-data" action="{{ route('tipo_envio.update', $tipoEnvio->id) }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('put')
            <div class="card ">
              <div class="card-header card-header-success card-header-icon">
                <div class="card-icon">
                  <i class="fas fa-shipping-fast fa-2x"></i>
                </div>
                <h4 class="card-title">Editar Tipo envio</h4>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('tipo_envio.index') }}" class="btn btn-sm btn-success">{{ __('Regresar a la lista') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">Nombre</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('nombre') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('nombre') ? ' is-invalid' : '' }}" name="nombre" id="input-name" type="text" placeholder="Nombre" value="{{ $tipoEnvio->nombre,old('nombre') }}" required="true" aria-required="true"/>
                      @include('alerts.feedback', ['field' => 'nombre'])
                    </div>
                  </div>
                </div>
                
              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-success">Editar</button>
              </div>
            
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/tipo_envios/index.blade.php
@extends('layouts.app', ['activePage' => 'tipo envio', 'menuParent' => 'catalogos', 'titlePage' => __('Tipo Envio')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-success card-header-icon">
                <div class="card-icon">
                  <i class="fas fa-shipping-fast fa-2x"></i>
                </div>
                <h4 class="card-title">Tipo Envios</h4>
              </div>
              <div class="card-body">
                @can('create', App\User::class)
                  <div class="row">
                    <div class="col-12 text-right">
                      <a href="{{ route('tipo_envio.create') }}" class="btn btn-sm btn-success">Agregar Tipo</a>
                    </div>
                  </div>
                @endcan
                <div class="table-responsive">
                  <table id="datatables" class="table table-striped table-no-bordered table-hover" style="display:none">
                    <thead class="text-primary">
                      <th class="desktop">
                          Nombre
                      </th>
                      @can('manage-users', App\User::class)
                        <th class="text-right desktop">
                          {{ __('Acciones') }}
                        </th>
                      @endcan
                    </thead>
                    <tbody>
                      @foreach($tipoEnvio as $envio)
                        <tr>
                          <td>{{$envio->nombre}}</td>
                          <td class="td-actions text-right">
                              <form action="{{ route('tipo_envio.destroy', $envio->id) }}" method="post">
                                  @csrf
                                  @method('delete')
                                  <a rel="tooltip" class="btn btn-warning btn-link" href="{{ route('tipo_envio.show', $envio->id) }}" data-original-title="" title="">
                                    <i class="material-icons">visibility</i>
                                    <div class="ripple-container"></div>
                                  </a>
                                  <a rel="tooltip" class="btn btn-success btn-link" href="{{ route('tipo_envio.edit', $envio->id) }}" data-original-title="" title="">
                                    <i class="material-icons">edit</i>
                                    <div class="ripple-container"></div>
                                  </a>
                                  <button type="button" class="btn btn-danger btn-link"
                                     data-original-title="" title="" onclick="            Swal.fire({
                                          title: 'Estás seguro?',
                                          text: 'Se borrará el registro!',
                                          type: 'warning',
                                          showCancelButton: true,
                                          buttonsStyling: false, 
                                          confirmButtonClass: 'btn btn-danger',
                                          cancelButtonClass: 'btn btn-success',
                                          confirmButtonText: 'Si, borralo!',
                                          cancelButtonText: 'No, quiero conservarlo!'
                                       }).then((result) => {
                                            if (result.value) {
                                                this.parentElement.submit()
                                            }
                                       })">
                                      <i class="material-icons">close</i>
                                      <div class="ripple-container"></div>
                                    </button>
                              </form>
                          </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
@endsection

@push('js')
  <script>
    $(document).ready(function() {
      $('#datatables').fadeIn(1100);
      $('#datatables').DataTable({
        "pagingType": "full_numbers",
        "lengthMenu": [
          [10, 25, 50, -1],
          [10, 25, 50, "Todos"]
        ],
        responsive: true,
        language: {
          search: "_INPUT_",
          searchPlaceholder: "Buscar envios",
        },
        "columnDefs": [
          { "orderable": false, "targets": 1 },
        ],
      });
    });
  </script>
@endpush

resources/views/tipo_envios/show.blade.php
@extends('layouts.app', ['activePage' => 'envio', 'menuParent' => 'catalogos', 'titlePage' => __('Tipo Envio')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" enctype="multipart/form-data" action="{{ route('tipo_envio.update', $tipoEnvio) }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('put')

            <div class="card ">
              <div class="card-header card-header-success card-header-icon">
                <div class="card-icon">
                  <i class="fas fa-shipping-fast fa-2x"></i>
                </div>
                <h4 class="card-title">Consulta Tipo Envio</h4>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('tipo_envio.index') }}" class="btn btn-sm btn-success">{{ __('Regresar a la lista') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">Nombre</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('nombre') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('nombre') ? ' is-invalid' : '' }}" name="nombre" id="input-name" type="text" placeholder="Nombre" value="{{ $tipoEnvio->nombre }}" required="true" aria-required="true" disabled/>
                      @include('alerts.feedback', ['field' => 'nombre'])
                    </div>
                  </div>
                </div>

              <div class="card-footer ml-auto mr-auto">
                <form action="{{ route('tipo_envio.destroy', $tipoEnvio->id) }}" method="post">
                    @csrf
                    @method('delete')
                    <a rel="tooltip" class="btn btn-success" href="{{ route('tipo_envio.edit', $tipoEnvio->id) }}" data-original-title="" title=""> Editar
                    </a>
                    
                    <input type="submit" class="btn btn-danger" value="Eliminar">
                </form>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection