routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EmployeeController;
use App\Salida;

Route::get('/', function () {
  return redirect('login');
});

Auth::routes();

/* Rutas estaticas */
Route::get('home', 'HomeController@index')->name('home');
Route::get('dashboard', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('role', 'RoleController', ['except' => ['show', 'destroy']]);
    Route::resource('user', 'UserController', ['except' => ['show']]);
    
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

    Route::resource('almacen','AlmacenController');
    Route::resource('proveedor','ProveedorController');
    Route::resource('mensajero','MensajeroController');
    Route::resource('rack','RackController');
    Route::resource('ubicacion','UbicacionController');
    Route::resource('entrada','EntradaController');
    Route::resource('cliente','ClienteController');
    Route::resource('tipocaja','TipoCajaController');
    Route::resource('paqueteria','PaqueteriaController');
    Route::resource('detalle_entrada','DetalleEntradaController');
    Route::resource('materiales','MaterialController');
    Route::resource('producto','ProductoController');
    Route::resource('lote_producto','LoteProductoController');
    Route::resource('recolector','RecolectorController');

    Route::resource('estatus_factura','EstatusFacturaController');
    Route::resource('tipo_entrada','TipoEntradaController');
    Route::resource('conductor','ConductorController');    
    Route::resource('tipo_salida','TipoSalidaController');
    Route::resource('familia_producto','FamiliaProductoController');
    Route::resource('tipo_envio','TipoEnvioController');
    Route::resource('salida','SalidaController');    
    Route::resource('factura','FacturaController');   
    Route::resource('detalle_factura','DetalleFacturaController');

    Route::get('guia/{guia}/{factura}/edit','GuiaController@edit')->name('guia.editar');

    Route::resource('guia','GuiaController');
    Route::resource('ruta_embarque','RutaEmbarqueController');
    Route::post('/producto/imprimir/etiqueta',[App\Http\Controllers\ProductoController::class, 'getImprimirEtiquetas'])->name('producto.imprimir.etiqueta');
    Route::get('/producto/info/etiqueta',[App\Http\Controllers\ProductoController::class, 'getInfoEtiquetas'])->name('producto.info.etiqueta');
    Route::post('/rack/imprimir/etiqueta',[App\Http\Controllers\RackController::class, 'getImprimirEtiquetas'])->name('rack.imprimir.etiqueta');
    Route::get('/rack/info/etiqueta',[App\Http\Controllers\RackController::class, 'getInfoEtiquetas'])->name('rack.info.etiqueta');
    Route::get('/facturas/notificacion', [App\Http\Controllers\FacturaController::class, 'getFacturasPorSurtir'])->name('facturas.notificacion');
    Route::get('/facturas/notificacion', [App\Http\Controllers\FacturaController::class, 'getFacturasPorSurtir'])->name('facturas.notificacion');
    Route::get('/facturas/detalles', [App\Http\Controllers\FacturaController::class, 'getDetalle'])->name('facturas.detalles');
    Route::get('/facturas/crear_detalle/{id_factura}', [App\Http\Controllers\FacturaController::class, 'create_detalle'])->name('facturas.detalle_create');
    Route::get('/facturas/filtros', [App\Http\Controllers\FacturaController::class, 'filtros'])->name('facturas.filtros');
    Route::get('/facturas/consulta/filtros', [App\Http\Controllers\FacturaController::class, 'consultaFacturas'])->name('facturas.consulta');
    Route::get('/factura/{factura}/show', [App\Http\Controllers\FacturaController::class, 'showFactura'])->name('facturas.show');
    Route::get('/entrada/crear/detalle/{entrada}', [App\Http\Controllers\DetalleEntradaController::class, 'createDetalle'])->name('entrada.create.detalle');
    Route::get('/producto/crear/lote/{producto}', [App\Http\Controllers\LoteProductoController::class, 'createLote'])->name('producto.create.lote');
    Route::get('/home/consulta', [App\Http\Controllers\HomeController::class, 'consulta'])->name('consulta');
    Route::get('/home/consulta_factura', [App\Http\Controllers\HomeController::class, 'consulta_factura'])->name('consulta_factura');
    Route::get('/home/consulta_pie', [App\Http\Controllers\HomeController::class, 'consulta_pie'])->name('consulta_pie');
    Route::post('/salida/estatus/mensajero',[App\Http\Controllers\SalidaController::class, 'getEstatusMensajero'])->name('salida.estatus.mensajero');
    Route::post('/salida/asignacion/mensajero',[App\Http\Controllers\SalidaController::class, 'getAsignacionMensajero'])->name('salida.asignacion.mensajero');
    Route::post('/guia/imprimir/etiqueta',[App\Http\Controllers\GuiaController::class, 'getImprimirEtiquetas'])->name('guia.imprimir.etiqueta');
    Route::get('/guia/info/etiqueta',[App\Http\Controllers\GuiaController::class, 'getInfoEtiquetas'])->name('guia.info.etiqueta');

    Route::get('/visita', 'VisitaController@visita')->name('visita');
    Route::get('/tipocajas', 'VisitaController@tipoCajas')->name('tipocajas');
    Route::get('/tipo_entradas/{entrada}', 'VisitaController@tipoEntradas')->name('tipoentradas');
    Route::get('/detalle_entradas', 'VisitaController@detalleEntradas')->name('detalle_entradas');

    Route::get('/entradas/{tipo}', 'VisitaController@entradas')->name('entradas2');
    Route::get('/proveedores/{entrada}', 'VisitaController@proveedores')->name('proveedores');
    Route::get('/familia_productos/{producto}', 'VisitaController@familiaProductos')->name('familia_productos');
    Route::get('/racks/{almacen}', 'VisitaController@racks')->name('racks');
    Route::get('/ubicaciones/{rack}', 'VisitaController@ubicaciones')->name('ubicaciones');

    Route::get('/facturas/subir', function () {return view('facturas.upload');})->name('facturas.upload');
    Route::post('/facturas/guardar', 'FacturaController@subirFactura')->name('factura.guardar');
    Route::get('/productos/subir', function () {return view('productos.upload');})->name('productos.upload');
    Route::post('/productos/guardar', 'ProductoController@subirProducto')->name('producto.guardar');
    Route::post('/productos/confirmar-producto', 'ProductoController@confirmarProducto')->name('producto.confirmar');
    //Primer Camino
    Route::get('/entradas/{opc}/{tipoE}','VisitaController@entradas')->name('entradas');
    Route::get('/proveedores/{opc}/{entrada}','VisitaController@proveedores')->name('proveedores');
    Route::get('/familia_productos/{opc}/{proveedor}','VisitaController@familiaProductos')->name('familia_productos');

    Route::get('/racks/{opc}/{dato}','VisitaController@racks')->name('racks');
    Route::get('/ubicaciones/{opc}/{dato}','VisitaController@ubicaciones')->name('ubicaciones');
    Route::get('/lote_productos/{opc}/{dato}','VisitaController@loteProductos')->name('lote_productos');

    Route::get('/productos','VisitaController@productos')->name('productos');
    Route::get('/salidas/mensajero', [App\Http\Controllers\SalidaController::class, 'mensajero'])->name('salidas.upload');
    Route::get('/salidas/amensajero', [App\Http\Controllers\SalidaController::class, 'amensajero'])->name('salidas.asignacion');
});


//Rutas Android
Route::post('/setToken','RecolectorController@setToken')->name('setToken');
Route::post('/arreglo','FacturaController@password');
Route::post('/por-surtir','FacturaController@getPorSurtir');
Route::post('/todas','FacturaController@getTodas');
Route::post('/get-factura','FacturaController@getFactura');
Route::post('/actualizar-factura','FacturaController@actualizarFactura');
Route::post('/recolectores','RecolectorController@getRecolectores')->name('recolectores');
Route::post('/ver-ubicaciones','UbicacionController@getUbicaciones');
Route::post('/ver-productos','ProductoController@getProductos');
Route::post('/subir-fotos','FacturaController@subirFotos');
Route::post('/actualizar-lote','UbicacionController@actualizarLote');
Route::post('/ver-detalles','DetalleFacturaController@getDetalles');

Route::post('/get-estatus-factura','EstatusFacturaController@getAllEstatus');
Route::post('/get-producto','ProductoController@getProducto');
Route::post('/get-ubicacion','UbicacionController@getUbicacion');
Route::post('/get-almacenes', function () {return App\ListHelper::getAllAlmacenes();});
Route::post('/get-via-embarques', function () {return App\ListHelper::getAllPaqueterias();});
Route::post('/actualizar-estatus-factura','FacturaController@actualizarEstatus');
// Route::get('/get-tipos-envio','EstatusFacturaController@getAllEstatus');


Route::post('/modificar-lotes','LoteProductoController@modificarLotes');
Route::post('/asignar-ubicacion','LoteUbicacionController@asignarUbicacionToProduct');
Route::post('/lotesByUbicacion','LoteProductoController@lotesByUbicacion');

app/Rack.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Rack extends Model
{
    use HasFactory;
    protected $table = 'c_rack';
    protected $fillable = [
        'c_almacene_id',
        'pasillo',
        'fila1',
        'alto_fila1',
        'ancho_fila1',
        'fila2',
        'alto_fila2',
        'ancho_fila2',
        'capturado_por',
        'actualizado_por',
    ];

    public function almacen(){
        return $this->belongsTo('App\Almacen','c_almacene_id');
    }
    
    public function ubicaciones()
    {
        return $this->hasMany('App\Ubicacion');
    }
}

app/Http/Controllers/RackController.php
<?php

namespace App\Http\Controllers;

use App\Rack;
use App\Almacen;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use PDF;
use SimpleSoftwareIO\QrCode\Facades\QrCode as FacadesQrCode;
use Illuminate\Support\Facades\Auth;

class RackController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($qrCodes = [])
    {
        if(!count($qrCodes))
            return view('racks.index', ['racks' => Rack::all(),'qrCodes'=>$qrCodes]);
        return view('racks.index', ['racks' => Rack::all(),'qrCodes'=>$qrCodes,'alert'=>"QRs generados con exito"])->withStatus('Registro creado correctamente.');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('racks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->request->add(['capturado_por' => Auth::user()->name]);
        $request->request->add(['actualizado_por' => Auth::user()->name]);
        Rack::create($request->all());
        return redirect()->route('rack.index')->withStatus(__('Registro creado correctamente.'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Rack  $rack
     * @return \Illuminate\Http\Response
     */
    public function show(Rack $rack)
    {
        return view('racks.show',compact('rack'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Rack  $rack
     * @return \Illuminate\Http\Response
     */
    public function edit(Rack $rack)
    {
        return view('racks.edit',compact('rack'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Rack  $rack
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Rack $rack)
    {
        $request->request->add(['actualizado_por' => Auth::user()->name]);
        $rack->update($request->all());
        return redirect()->route('rack.index')->withStatus(__('El registro fue actualizado.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Rack  $rack
     * @return \Illuminate\Http\Response
     */
    public function destroy(Rack $rack)
    {
        $rack->ubicaciones()->delete();
        $rack->delete();
        return redirect()->route('rack.index')->withStatus(__('El registro fue borrado.'));
    }
    public function getInfoEtiquetas(Request $request)
    {
        return Rack::find($request->id_rack);
    }

    public function getImprimirEtiquetas(Request $request)
    {
        $rack =  Rack::find($request->id_rack);
        $request = $request->all();

        $ubicaciones = DB::select("SELECT cu.id, identificador, x, y, cr.pasillo
                                FROM c_ubicacione cu
                                INNER JOIN c_rack cr
                                ON cu.rack_id = cr.id
                                where cr.id =$rack->id");

        foreach ($ubicaciones as $ubicacion) {
            $QRs[] = ['nombre'=>'Pasillo-'.$ubicacion->pasillo.' fila-'.$ubicacion->identificador.' Anaquel-'.$ubicacion->x.' Estante-'.$ubicacion->y, 'img' => $this->generarQR($ubicacion->id)];
        }

        return $this->index($QRs);
    }


    public function generarQR($idUbicacion)
    {
        $qrcode = base64_encode(FacadesQrCode::format('png')->size(200)->errorCorrection('H')->generate($idUbicacion.''));
        return $qrcode;
    }

}

resources/views/racks/create.blade.php
@extends('layouts.app', ['activePage' => 'rack', 'menuParent' => 'catalogos', 'titlePage' => __('Pasillo')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <form method="post" enctype="multipart/form-data" action="{{ route('rack.store') }}"
                        autocomplete="off" class="form-horizontal">
                        @csrf
                        <div class="card">
                            <div class="card-header card-header-success card-header-icon">
                                <div class="card-icon">
                                    <i class="fas fa-grip-vertical fa-2x"></i>
                                </div>
                                <h4 class="card-title">Agregar Pasillo</h4>
                            </div>
                            @include('racks.layout.form',['show' => false,'edit' => false, 'create' => true])
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/racks/edit.blade.php
@extends('layouts.app', ['activePage' => 'rack', 'menuParent' => 'catalogos', 'titlePage' => __('Pasillo')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <form method="post" enctype="multipart/form-data" action="{{ route('rack.update', $rack->id) }}"
                        autocomplete="off" class="form-horizontal">
                        @csrf
                        @method('put')
                        <div class="card ">
                            <div class="card-header card-header-success card-header-icon">
                                <div class="card-icon">
                                    <i class="fas fa-grip-vertical fa-2x"></i>
                                </div>
                                <h4 class="card-title">Editar Pasillo</h4>
                            </div>
                            @include('racks.layout.form',['show' => false,'edit' => true, 'create' => false])
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/racks/etiquetas.blade.php
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Etiquetas Qr Mexlab</title>
    <style>
        @media print {

            html,
            body {
                height: 99%;
            }
        }

        .page-break {
            page-break-after: always;
        }

        .page-break:last-child {
            page-break-after: auto;
        }

        table {
            width: 100%;
        }

        tr{
            margin-top: 5px;
        }

    </style>
</head>

<body>
    @php
        $contador = 0;
    @endphp
    <table>
        @foreach ($qrcode as $qr)
            @if ($contador == 0)
                @php
                    $contador = 3;
                @endphp
                <tr>
            @endif
            <td style="border: 1px solid black">
                <img style="margin-bottom: 0;margin-top:30px;" src="data:image/png;base64, {!! $qr['qr'] !!}">
                <p style="text-align: center;margin-top: 0;">{{ $qr['slot'] }}</p>
            </td>
            @if ($contador == 0)
                </tr>
            @endif
            @php
                $contador--;
            @endphp
        @endforeach
    </table>
</body>

</html>

resources/views/racks/index.blade.php
@extends('layouts.app', ['activePage' => 'rack', 'menuParent' => 'catalogos', 'titlePage' => __('Pasillo')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">

          @isset($alert)
              <div class="alert alert-success alert-dismissible fade show" role="alert">
                  <strong>{{$alert}}</strong>
                  <br>

                  @if (count($qrCodes))
                      <button class='btn btn-sm btn-primary' onclick="clickbutton()">Descargar Qrs</button>
                  @endif
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
                  <br>
                  @php($cont=0)
                  @foreach ($qrCodes as $qrCode)
                          <a id="enlace-{{$cont++}}" class="btn btn-sm btn-primary" href="data:image/png;base64, {{$qrCode['img']}}" download="{{$qrCode['nombre']}}">{{$qrCode['nombre']}}</a>
                  @endforeach
              </div>
          @endisset

            <div class="card">
              <div class="card-header card-header-success card-header-icon">
                <div class="card-icon">
                  <i class="fas fa-grip-vertical fa-2x"></i>
                </div>
                <h4 class="card-title">Pasillos</h4>
              </div>
              <div class="card-body">
                @can('create', App\User::class)
                  <div class="row">
                    <div class="col-12 text-right">
                      <a href="{{ route('rack.create') }}" class="btn btn-sm btn-success">Agregar Pasillo</a>
                    </div>
                  </div>
                @endcan
                <div class="table-responsive">
                  <table id="datatables" class="table table-striped table-no-bordered table-hover" style="display:none;width:100%">
                    <thead class="text-primary">
                      <th class="desktop">Almacen</th>
                      <th class="desktop">Pasillo</th>
                      {{-- <th class="desktop">Fila 1</th>
                      <th class="desktop">Fila 2</th> --}}
                      @can('manage-users', App\User::class)
                        <th class="text-right desktop">
                          {{ __('Acciones') }}
                        </th>
                      @endcan
                    </thead>
                    <tbody>
                      @foreach($racks as $rack)
                        <tr>
                          <td>{{$rack->almacen->nombre}}</td>
                          <td>{{$rack->pasillo}}</td>
                          {{-- <td>{{$rack->fila1}}</td>
                          <td>{{$rack->fila2}}</td> --}}
                          <td class="td-actions text-right">
                              <form action="{{ route('rack.destroy', $rack->id) }}" method="post">
                                  @csrf
                                  @method('delete')
                                  <!-- Button trigger modal -->
                                  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" onclick="mostrar({{$rack->id}})">
                                    <i class="fas fa-tags"></i>
                                  </button>
                                  <a rel="tooltip" class="btn btn-warning btn-link" href="{{ route('rack.show', $rack->id) }}" data-original-title="" title="">
                                    <i class="material-icons">visibility</i>
                                    <div class="ripple-container"></div>
                                  </a>
                                  <a rel="tooltip" class="btn btn-success btn-link" href="{{ route('rack.edit', $rack->id) }}" data-original-title="" title="">
                                    <i class="material-icons">edit</i>
                                    <div class="ripple-container"></div>
                                  </a>
                                  <button type="button" class="btn btn-danger btn-link" data-original-title="" title="" onclick="Swal.fire({
                                    title: 'Estás seguro?',
                                    text: 'Se borrará el registro!',
                                    type: 'warning',
                                    showCancelButton: true,
                                    buttonsStyling: false,
                                    confirmButtonClass: 'btn btn-danger',
                                    cancelButtonClass: 'btn btn-success',
                                    confirmButtonText: 'Si, borralo!',
                                    cancelButtonText: 'No, quiero conservarlo!'
                                }).then((result) => {
                                    if (result.value) {
                                        this.parentElement.submit()
                                    }
                                })">
                                      <i class="material-icons">close</i>
                                      <div class="ripple-container"></div>
                                  </button>
                              </form>
                          </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                  <div class="modal-content">
                      <div class="modal-header">
                          <div class="card-icon">
                              <i class="fas fa-tags fa-2x" style="color:purple"></i>
                          </div>
                      <h5 class="modal-title" id="exampleModalLabel">Etiqueta Qr</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                      </div>
                      <div class="modal-body">
                      <form method="post" action="{{route('rack.imprimir.etiqueta')}}" class="form-horizontal" enctype="multipart/form-data">
                          @csrf
                          @method('post')
                          <div class="row">
                            <div class="col-4"></div>
                              <div class="col-4 text-center">
                                  <label for="cantidad">Pasillo</label>
                                  <input class="form-control" type="text" name="pasillo" id="pasillo" disabled>
                              </div>
                              <input type="hidden" name="id_rack" id="id_rack">
                          </div>
                      </div>
                      <div class="modal-footer ml-auto mr-auto">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                      <button type="submit" class="btn btn-primary">Imprimir</button>
                      </div>
                  </form>
                  </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
</div>
</div>
@endsection
@push('js')
  <script>
    $(document).ready(function() {
      $('#datatables').fadeIn(1100);
      $('#datatables').DataTable({
        "pagingType": "full_numbers",
        "lengthMenu": [
          [10, 25, 50, -1],
          [10, 25, 50, "Todos"]
        ],
        responsive: true,
        language: {
          search: "_INPUT_",
          searchPlaceholder: "Buscar racks",
        },
        "columnDefs": [
          { "orderable": false, "targets": 4 },
        ],
      });
    });
    function mostrar(id){
            var token = "{{ csrf_token() }}";
            $.ajax({
                url: "{{ route('rack.info.etiqueta') }}",
                type: 'GET',
                dataType: "JSON",
                data: {
                    "_token": token,
                     "id_rack": id
                },
                success: function(response) {
                    console.log(response)
                    $("#pasillo").val(response.pasillo);
                    $("#id_rack").val(response.id);
                    console(response);
                }
            });
        }

      function clickbutton() {
          let size = {{count($qrCodes)}};
          let i=0;

          for(i=0; i<size; i++){
              // console.log('enlace-'+(i));
              document.getElementById('enlace-'+(i)).click();
          }
          // while(true){
          //     console.log('enlace-'+(i++));
          //     try{
          //         document.getElementById('enlace-'+(i++)).click();
          //     }catch(error){
          //         break;
          //     }
          // }
      }
    </script>
@endpush

resources/views/racks/show.blade.php
@extends('layouts.app', ['activePage' => 'rack', 'menuParent' => 'catalogos', 'titlePage' => __('Pasillo')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <form method="post" enctype="multipart/form-data" action="{{ route('rack.update', $rack) }}"
                        autocomplete="off" class="form-horizontal">
                        @csrf
                        @method('put')
                        <div class="card">
                            <div class="card-header card-header-success card-header-icon">
                                <div class="card-icon">
                                    <i class="fas fa-grip-vertical fa-2x"></i>
                                </div>
                                <h4 class="card-title">Consultar Pasillo</h4>
                            </div>
                            @include('racks.layout.form',['show' => true,'edit' => false, 'create' => false])
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection